### ISSUE TITLE
Write a user story

### ISSUE THREAD

**Issue by meeday** [meeday/engineer-app#1]

**Comment by JoeDodgson** [comment]
## MVP
* AS A Project Manager, I WANT to create a new project risk management site SO THAT there is an area to add project information
* AS A Project Manager, I WANT to add new Engineers to a project SO THAT they have access to the project information
* AS AN Engineer, I WANT to create a login profile on the project risk management site SO THAT I can access the project site
* AS AN Engineer, I WANT to view project risks information SO THAT I know what areas of the design can be improved
* AS AN Engineer, I WANT to view the locations of project risks on a map SO THAT I know where they are in relation to the design
* AS AN Engineer, I WANT to add a new risk to a project SO THAT the risk can be identified and managed
* AS AN Engineer, I WANT to edit an existing project risk SO THAT I can update information related to it
* AS AN Engineer, I WANT to see the latest changes or addition of risks SO THAT I am aware of the latest changes
* AS AN Engineer, I WANT to comment on risks SO THAT I can raise any questions
* AS AN Engineer, I WANT to view other users' comments on risks SO THAT I can see other's questions
* AS A Project Manager, I WANT to be able to export a list of risks in .csv format SO THAT I can issue an Excel workbook of risks to my client

## Future releases
* AS A site admin, I WANT to be able to change the access rights of other project risk management site users SO THAT I can control who has access to project information
* AS AN Engineer, I WANT to add and edit project departures SO THAT I know what areas of the design are not compliant to standards
* AS AN Engineer, I WANT to add and edit project assumptions SO THAT there is a record of engineering judgements applied to produce the design
* AS AN Engineer, I WANT to reference risks, departures and assumptions with each other SO THAT related information is grouped together
* AS AN Engineer, I WANT to view all change history of risks, departures and assumptions SO THAT I can see how design changes have influenced these items
* AS A Senior Engineer, I WANT to mark risks, departures or assumption as checked SO THAT other project team members have confidence that the item is valid
* AS A Project Manager / Project Director, I WANT to mark risks, departures or assumption as approved SO THAT other project team members have confidence that the item is valid
